services:
  fn_db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      TZ: Europe/Moscow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5438:5432"

  bot:
    build: .
    restart: always
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      DB_HOST: fn_db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    depends_on:
      - fn_db

volumes:
  postgres_data:
#